language:
  - ruby
before_install:
  - sudo apt-get update -qq
  - gem update bundler
bundler_args: --verbose
rvm:
  - 2.1
  - 2.2
  - 2.3.0
gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/rails_edge.gemfile
before_script:
  - bundle list
  - sudo apt-get install -y wkhtmltopdf
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
env: WKHTMLTOPDF_BIN=/usr/bin/wkhtmltopdf
script:
  - bundle exec rake
matrix:
  allow_failures:
    - gemfile: gemfiles/rails_edge.gemfile
